# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5236d3053a79a69751f7cadec01df83e1671bddb3125d080004c510e37a34c5054079afbf8e61e90888076ce943463821c42666d972cb606f9de5ad65cec1aa8

test:
  secret_key_base: 0e37377e5765c0f908cd3b6d7a7583c59b8b508e820477363c4fdd123ea9fac5113b8bea88a02899808a6643c8eb669ea76dcc0e1a840213dca588d16fe8638f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
